/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kata.h"

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->x.x_val, (u_int *) &objp->x.x_len, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->arr.arr_val, (u_int *) &objp->arr.arr_len, 2,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->r))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->xy.xy_val, (u_int *) &objp->xy.xy_len, 15,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
