/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"


void
add_prog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	intpair  metro_1_arg;
	int  *result_2;
	intpair  akr_1_arg;
	intpair  *result_3;
	intpair  pinak_1_arg;
	intpair  *result_4;
	intpair  gin_1_arg;
int i;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	
         metro_1_arg.r = 2;
         metro_1_arg.xy.xy_len = 2;
         metro_1_arg.xy.xy_val = (int *) malloc(2*sizeof(int));        

         metro_1_arg.pin.pin_len = 2;
         metro_1_arg.pin.pin_val = (double *) malloc(2*sizeof(double));         

         metro_1_arg.x.x_len = 2;
         metro_1_arg.x.x_val = (int *) malloc(2*sizeof(int)); 
         metro_1_arg.x.x_val[0] = 1;
         metro_1_arg.x.x_val[1] = 2;
        
         metro_1_arg.y.y_len = 2;
         metro_1_arg.y.y_val = (int *) malloc(2*sizeof(int)); 
         metro_1_arg.y.y_val[0] = 1;
         metro_1_arg.y.y_val[1] = 2;

	result_1 = metro_1(&metro_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else printf("Metro x = %lf \n" , *result_1);

	result_2 = akr_1(&metro_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else printf("Eswt gin = %d \n" , *result_2);

	result_3 = pinak_1(&metro_1_arg, clnt);
	if (result_3 == (intpair *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else {
        printf("Mesh thmh x: %f \n", result_3->pin.pin_val[0] );	
        
       
        printf("Mesh thmh y: %f \n", result_3->pin.pin_val[1] );	
      }  

	result_4 = gin_1(&metro_1_arg, clnt);
	if (result_4 == (intpair *) NULL) {
		clnt_perror (clnt, "call failed");
	}

else {  printf("Return is: ");
        for(i = 0; i<result_4->xy.xy_len; i++)
        printf(" %d \n", result_4->xy.xy_val[i]);
}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host);
exit (0);
}
